# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory_info',
            name='memory_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
