# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_memory_info_memory_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='network_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_id', models.CharField(max_length=20)),
                ('network_key', models.CharField(max_length=20)),
                ('network_in', models.IntegerField(default=0)),
                ('network_out', models.IntegerField(default=0)),
                ('network_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
